import {
    BookIcon,
    FlameIcon,
    TrendingUp,
} from "lucide-react";
import { TabItem } from "../../types/types";

export const BOOK_ITEMS: TabItem[] = [
    {
        category: "Self Development",
        icon: BookIcon,
        items: [
            "The Subtle Art of Not Giving a F*ck - Mark Manson",
            "Atomic Habits - James Clear",
            "Mastery - Robert Greene",
            "The Alchemist - Paulo Coelho",
            "Deep Work - Cal Newport",
            "Think and Grow Rich - Napoleon Hill",
            "The 7 Habits of Highly Effective People - Stephen Covey",
            "The Courage to Be Disliked - Ichiro Kishimi & F. Koga",
            "Think Like a Monk - Jay Shetty",
            "Give and Take - Adam Grant",
            "Quit - Daniel Kahneman",
            "No Excuses - Brian Tracy",
            "How To Win Friends and Influence People - Dale Carnegie",
            "The Enemy Called Average - John Mason",
            "Keep Going - Austin Kleon",
            "Building a Second Brain - Tiago Forte",
            "Ikigai - Hector Garcia & Francesc Miralles",
            "Side Hustle Bible - James Altucher",
            "The Charisma Myth - Olivia Fox Cabane",
            "46 rules of Genius - Marty Neumeier",
        ],
    },
    {
        category: "Design & Tech",
        icon: FlameIcon,
        items: [
            "The Design of Everyday Things - Donald Norman",
            "Don't Make Me Think - Steve Krug",
            "The Laws of UX - Jon Yablonski",
            "Refactoring UI - Adam Wathan & Steven Schoger",
            "Atomic Design - Brad Frost",
            "Hooked - Nir Eyal & Ryan Hoover",
            "Design is a job - Mike Monteiro",
            "The UX Book - Rex Hartson & Pardha S. Pyla",
            "Designing Brand Identity - Alina Wheeler",
            "Identity Designed - David Airey",
            "The Art of Noticing - Rob Walker",
            "Content Everywhere - Sara Wachter-Boettcher",
            "Clean Architecture - Robert C. Martin",
            "Clean Code - Robert C. Martin",
            "Grokking Algorithms - Aditya Y. Bhargava",
            "Cracking the Coding Interview",
            "You Don't Know JS - Kyle Simpson",
            "Nicely Said - Nicole Fenton & Kate Kiefer Lee",
            "Scary Smart: The future of AI and how you can save the world - Mo Gawdat",
            "Release It: Design and Deploy Production-Ready Software - Michael T. Nygard",
            "The Coming Wave - Mustafa Suleyman",
            "Life After Google - George Gilder",
            "The Business Value of Developer Relations - Mary Thengvall",
            "Community Building on the Web - Amy Jo Kim",
        ],
    },
    {
        category: "Others",
        icon: TrendingUp,
        items: [
            "Zero to One - Peter Thiel",
            "48 Laws of Power - Robert Greene",
            "Rework - Jason Fried",
            "Never Split the Difference - Chris Voss & Tahl Raz",
            "Rich Dad Poor Dad - Robert Kiyosaki",
            "The Monk Who Sold His Ferrari - Robin Sharma",
            "The Psychology of Money - Morgan Housel",
            "The Bottom Billion - Paul Collier",
            "The Missing Crypto Queen - Jamie Bartlett",
            "The Cryptopians - Laura Shin",
            "Outlive: The Science and Art of Longevity - Peter Attia",
            "Influence: The Psychology of Persuasion - Robert B. Cialdini",
            "The Richest Man in Babylon - George S. Clason",
            "There was a country - Chinua Achebe",
            "Range: Why generalists triumph in a specialized world - David Epstein ",
            "It didn't start with you - Mark Wolynn",
            "The Art of Explanation - Lee Lefever",
            "The Anti-Social Network - Ben Mezrich",
            "Your Money or Your Life - Vicki Robin and Joe Dominguez",
            "Einstein: His Life and Universe - Walter Isaacso",
        ],
    },
];
