import {
    SiJavascript,
    SiReact,
    SiNextdotjs,
    SiCss3,
    SiSass,
    SiTailwindcss,
    SiTypescript,
    SiNodedotjs,
    SiGit,
    SiNotion,
    SiAdobephotoshop,
    SiFigma,
    SiGraphql,
    SiFirebase,
    SiSupabase,
    SiMarkdown,
    SiNetlify,
    SiGitlab,
} from "react-icons/si";
import { TechToolsProps } from "../../lib/types";

export const tools: TechToolsProps[] = [
    { name: "Javascript", icon: SiJavascript, color: "#F7DF1E" },
    { name: "React", icon: SiReact, color: "#61DAFB" },
    { name: "Next.js", icon: SiNextdotjs, color: "#000000" },
    { name: "CSS", icon: SiCss3, color: "#1572B6" },
    { name: "SASS", icon: SiSass, color: "#E0234E" },
    { name: "Tailwind CSS", icon: SiTailwindcss, color: "#06B6D4" },
    { name: "TypeScript", icon: SiTypescript, color: "#3178C6" },
    { name: "Node.js", icon: SiNodedotjs, color: "#8CC84B" },
    { name: "Git", icon: SiGit, color: "#F05032" },
    { name: "Notion", icon: SiNotion, color: "#F0F0F0" },
    { name: "Adobe Photoshop", icon: SiAdobephotoshop, color: "#31A8FF" },
    { name: "Figma", icon: SiFigma, color: "#F24E1E" },
    { name: "GraphQL", icon: SiGraphql, color: "#E10098" },
    { name: "Firebase", icon: SiFirebase, color: "#	#FFCA28" },
    { name: "Supabase", icon: SiSupabase, color: "#3E4C59" },
    { name: "Markdown", icon: SiMarkdown, color: "#0f0f0f" },
    { name: "Netlify", icon: SiNetlify, color: "#00C48C" },
    { name: "GitLab", icon: SiGitlab, color: "#E24329" },
];
